### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shivamkonkar**
Added Ending for Documentation

### CODE REVIEW

**Comment by shivamkonkar** [comment]
this will help people to know where documentation ends

**Comment by pmingram** [comment]
Doesn't the end of the file achieve the same result?

**Comment by iiCe89** [comment]
this really isn't need imo 😐

**Comment by shivamkonkar** [comment]
Rest documentation was correct just decided to do some ending tweaks _cool_

**Comment by alfiehopkin** [comment]
I think there will be a lot of these PRs submit due to this - https://hacktoberfest.digitalocean.com/

**Comment by ollieread** [comment]
There is absolutely no reason, or need, to add something like this. Your paper-thin ploy to gain a HacktoberFest t-shirt can be seen through by all that those are completely blind to all visible spectrums of light.

@shivamkonkar You may now consider yourself sufficiently chastised, and I hope you are ashamed.

**Comment by shivamkonkar** [comment]
Iam very sorry about my work. Iam ashamed. I have no interest winning
t-shirt now. I will try do some real work tomorrow

Really Sorry 🙏

**Pull request closed without merging**
